### ISSUE TITLE
[Feature Request] Clicking on the card should go to the challenge

### ISSUE THREAD

**Issue by anushibin007** [Mah1ndra/portfolio-ctf#2]
In the main page (localhost/index.html), when we click on the challenge card, it does not go to the challenge. We are instead supposed to click on the "Click here to begin" link to start the challenge. That does not seem very intuitive.

The expected behavior would be to click on the card and get redirected to the challenge.

**Comment by blueharoon** [comment]
changes implemented via cb3af11e8cc053c370e4f474af1aa0f678739880
